# name: Build latest from main
 
# on:
#   push:
#     branches: [ main ] # This watches the branch called "main"
 
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
 
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
 
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
 
#       - name: Build image and push to GitHub Container Registry
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: 'ghcr.io/sethaj/sharkinfo-docker-k8s/sharkinfo-docker-k8s:${{ github.sha }}, ghcr.io/sethaj/sharkinfo-docker-k8s/sharkinfo-docker-k8s:latest'
#           file: Dockerfile

